spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/task-reviewer}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  application:
    name: task_reviewer
  liquibase:
    default-schema: public
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  tasks-path: ${TASKS_PATH:classpath:tasks}
